In [1]:
aList = ["John",33,"Toronto",True]
print(aList)

['John', 33, 'Toronto', True]


In [2]:
aList = ["Ryan Arya",2020071040,"Desain Analisis Algoritma","9 Sep 2021","Universitas Pembangunan Jaya"]
print(aList)

['Ryan Arya', 2020071040, 'Desain Analisis Algoritma', '9 Sep 2021', 'Universitas Pembangunan Jaya']


In [3]:
bin_color=['Red','Green','Blue','Yellow']
bin_color[1]

'Green'

In [4]:
aList = ["Ryan Arya",2020071040,"Desain Analisis Algoritma","9 Sep 2021","Universitas Pembangunan Jaya"]
aList[1]

2020071040

In [5]:
aList = ["Ryan Arya",2020071040,"Desain Analisis Algoritma","9 Sep 2021","Universitas Pembangunan Jaya"]
aList[4]

'Universitas Pembangunan Jaya'

In [6]:
bin_color=['Red','Green','Blue','Yellow']
bin_color[0:3]

['Red', 'Green', 'Blue']

In [7]:
aList = ["Ryan Arya",2020071040,"Desain Analisis Algoritma","9 Sep 2021","Universitas Pembangunan Jaya"]
aList[0:3]

['Ryan Arya', 2020071040, 'Desain Analisis Algoritma']

In [8]:
bin_color=['Red','Green','Blue','Yellow']
for aColor in bin_color:
  print(aColor + "square")

Redsquare
Greensquare
Bluesquare
Yellowsquare


In [9]:
bin_List = ["Apel","Semangka","Jeruk","Anggur","Melon"]
for aList in bin_List:
  print("Buah " + aList)

Buah Apel
Buah Semangka
Buah Jeruk
Buah Anggur
Buah Melon


In [10]:
bin_color=('Red','Green','Blue','Yellow','Brown')
bin_color[1]

'Green'

In [11]:
bin_color[1:]

('Green', 'Blue', 'Yellow', 'Brown')

In [12]:
bin_Upj=('Universitas','Pembangunan','Jaya')
bin_Upj[1]

'Pembangunan'

In [13]:
bin_Upj

('Universitas', 'Pembangunan', 'Jaya')

In [14]:
my_tuple = ("pertama = 100","kedua = 200,400,600","ketiga = 300","Keempat = 300") 
print(my_tuple[2])

ketiga = 300


In [15]:
bin_colors ={"mannual_color":"Yellow","approved_color":"Green","refused_color":"Red"}
print(bin_colors)

{'mannual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [16]:
bin_colors.get("approved_color")

'Green'

In [17]:
bin_colors['approved_color']

'Green'

In [18]:
bin_colors['approved_color']="puprle"
print(bin_colors)

{'mannual_color': 'Yellow', 'approved_color': 'puprle', 'refused_color': 'Red'}


In [20]:
bin_key ={"Nama":"Ryan Arya","Nim":"2020071040","Prodi":"Informatika","Universitas":"UPJ"}
print(bin_key)

{'Nama': 'Ryan Arya', 'Nim': '2020071040', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [21]:
print(bin_key['Nama'])

Ryan Arya


In [22]:
print(bin_key.get('Nama'))

Ryan Arya


In [23]:
green = {'grass','leaves'}
print(green)

{'leaves', 'grass'}


In [24]:
red = {'bloods','grapes','grapes'}
print(red)

{'grapes', 'bloods'}


In [25]:
red = {'rose','blood','leaves','fire hydrant'}
yellow = {'dandelions','fire hydrant','leaves'}
print(yellow | red)
print(yellow & red)

{'rose', 'leaves', 'blood', 'dandelions', 'fire hydrant'}
{'fire hydrant', 'leaves'}


In [27]:
import pandas as pd
df = pd.DataFrame([
                   ['1','Fares',32,True],
                   ['2','Elena',23,False],
                   ['3','Steven',40,True]])

In [28]:
df.columns=['id','name','age','decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [29]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [30]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [31]:
import pandas as pd
df = pd.DataFrame([
                   ['1','Informatika',50,30,20],
                   ['2','Sistem Informasi',50,30,25],
                   ['3','Teknik Sipil',40,30,10]])

In [32]:
df.columns=['No','Prodi','Mahasiswa','Laki-laki','Perempuan']
df

No             Prodi  Mahasiswa  Laki-laki  Perempuan
0  1       Informatika         50         30         20
1  2  Sistem Informasi         50         30         25
2  3      Teknik Sipil         40         30         10

In [33]:
import numpy as np

In [34]:
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [35]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [36]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items==[]
  def push(self,item):
    self.items.append(item)
  def pop(self):
    return self.items[len(self.items)-1]
  def size(self):
    return len(self.item)

In [37]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

In [38]:
stack.pop()

'Yellow'

In [39]:
stack.isEmpty()

False

In [40]:
class Queue(object):
  def __init__(self):
    self.items=[]
  def isEmpty(self):
      return self.items == []
  def enqueue(self,item):
      self.items.insert(0,item)
  def dequeue(self):
      return self.items.pop()
  def size(self):
      return len(self.items)
queue=Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())
print(queue.dequeue())
print(queue.dequeue())

4
Red
Green
